---  
- name: Uninstall the Logging Transfer Solution
  hosts: all
  gather_facts: false
  ignore_errors: true 
  vars:
    kyndryl_folder: 'C:\Kyndryl\'
    job_logs: 'EventArchiver.log'
    upload_file: 'UploadFile.ps1'
  
  tasks:
    # Remove task schedule        
    - name: Delete scheduled task
      win_scheduled_task:
        name: "Logging Transfer Solution"
        state: absent 
      
    # Remove powershell script to upload files
    - name: Remove Powershell upload archive file
      win_file:
        path: "{{ kyndryl_folder }}{{ upload_file }}"
        state: absent  
    
    # Remove Job logs
    - name: Remove Job logs
      win_file:
        path: "{{ kyndryl_folder }}{{ job_logs }}"
        state: absent 

    # Remove registry settings
    - name: Remove registry keys
      win_shell: |
        # Check if registry folder exists. If not, add it 
        if (Test-Path -Path 'HKLM:\SOFTWARE\Kyndryl') {
            Remove-Item -Path 'HKLM:\SOFTWARE\Kyndryl'
        }
